#!/usr/bin/env python3
"""Generate web/web_battery.js — the {expression, expected} table the wasm
smoke test (web/test_web.js) checks the Emscripten build against.

The web build drops JIT/FFI/RESP/readline, so it can't run the full test.alc
suite; instead this asserts the wasm/clang codegen produces byte-identical
output to NATIVE alcove on a broad battery of expressions (the tagged-pointer,
float, and vector paths that historically miscompiled). Expected values are
DERIVED from native here — never hand-written — so they can't drift.

Sources (one expression per line, '#' comments ignored):
    web/web_exprs_lisp.txt   -> run through native ./alcove
    web/web_exprs_adder.txt  -> run through native ./adder

Run via `make gen-web-battery` (which builds ./alcove and ./adder first).
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
ANSI = re.compile(r"\x1b\[[0-9;]*m")
OUT = re.compile(r"Out\s*\[\d+\]:(.*)")


def read_exprs(path):
    out = []
    with open(path) as f:
        for ln in f:
            s = ln.rstrip("\n")
            if not s.strip() or s.lstrip().startswith("#"):
                continue
            out.append(s)
    return out


def native_eval(binary, exprs):
    """Run each expression through the native REPL and capture its printed
    result (last Out[...] segment, ANSI stripped). One process per expression
    keeps results isolated and order-independent."""
    results = []
    for e in exprs:
        p = subprocess.run([binary, "--noload"], input=e + "\n",
                           capture_output=True, text=True, timeout=60)
        clean = ANSI.sub("", p.stdout)
        segs = OUT.findall(clean)
        results.append(segs[-1].strip() if segs else "")
    return results


def js_array(name, exprs, expected):
    rows = []
    for e, x in zip(exprs, expected):
        rows.append(f"  [{js_str(e)}, {js_str(x)}],")
    return f"const {name} = [\n" + "\n".join(rows) + "\n];\n"


def js_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    alcove = os.path.join(ROOT, "alcove")
    adder = os.path.join(ROOT, "adder")
    for b in (alcove, adder):
        if not os.path.exists(b):
            sys.exit(f"gen_web_battery: {b} not built — run `make jit && make adder`")

    lisp_exprs = read_exprs(os.path.join(ROOT, "web/web_exprs_lisp.txt"))
    adder_exprs = read_exprs(os.path.join(ROOT, "web/web_exprs_adder.txt"))
    lisp_exp = native_eval(alcove, lisp_exprs)
    adder_exp = native_eval(adder, adder_exprs)

    out = os.path.join(ROOT, "web/web_battery.js")
    with open(out, "w") as f:
        f.write(
            "/* GENERATED by gen_web_battery.py — do not edit by hand.\n"
            " * Expressions: web/web_exprs_{lisp,adder}.txt; expected values are\n"
            " * native alcove/adder output. Regenerate: make gen-web-battery. */\n"
            "'use strict';\n")
        f.write(js_array("LISP", lisp_exprs, lisp_exp))
        f.write(js_array("ADDER", adder_exprs, adder_exp))
        f.write("module.exports = { LISP, ADDER };\n")
    print(f"gen_web_battery: wrote {out} "
          f"({len(lisp_exprs)} lisp + {len(adder_exprs)} adder cases)")


if __name__ == "__main__":
    main()
